
package cl.clarochile.webservices.ofertabolsaswsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ofertaBolsasWSDL", targetNamespace = "http://www.clarochile.cl/webservices/ofertaBolsasWSDL/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OfertaBolsasWSDL {


    /**
     * 
     * @param parameters
     * @return
     *     returns cl.clarochile.webservices.ofertabolsaswsdl.ConsultaBolsasResponse
     */
    @WebMethod(operationName = "ConsultaBolsas", action = "http://www.clarochile.cl/webservices/ofertaBolsasWSDL/ConsultaBolsas")
    @WebResult(name = "ConsultaBolsasResponse", targetNamespace = "http://www.clarochile.cl/webservices/ofertaBolsasWSDL/", partName = "parameters")
    public ConsultaBolsasResponse consultaBolsas(
        @WebParam(name = "ConsultaBolsasRequest", targetNamespace = "http://www.clarochile.cl/webservices/ofertaBolsasWSDL/", partName = "parameters")
        ConsultaBolsasRequest parameters);

}
