
package cl.clarochile.webservices.ofertabolsaswsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ofertaBolsasWSDL", targetNamespace = "http://www.clarochile.cl/webservices/ofertaBolsasWSDL/", wsdlLocation = "file:/home/luisnunez/HAVAS/LDI/ofertaBolsasWSDL/ofertaBolsasWSDL.wsdl")
public class OfertaBolsasWSDL_Service
    extends Service
{

    private final static URL OFERTABOLSASWSDL_WSDL_LOCATION;
    private final static WebServiceException OFERTABOLSASWSDL_EXCEPTION;
    private final static QName OFERTABOLSASWSDL_QNAME = new QName("http://www.clarochile.cl/webservices/ofertaBolsasWSDL/", "ofertaBolsasWSDL");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/luisnunez/HAVAS/LDI/ofertaBolsasWSDL/ofertaBolsasWSDL.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OFERTABOLSASWSDL_WSDL_LOCATION = url;
        OFERTABOLSASWSDL_EXCEPTION = e;
    }

    public OfertaBolsasWSDL_Service() {
        super(__getWsdlLocation(), OFERTABOLSASWSDL_QNAME);
    }

    public OfertaBolsasWSDL_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), OFERTABOLSASWSDL_QNAME, features);
    }

    public OfertaBolsasWSDL_Service(URL wsdlLocation) {
        super(wsdlLocation, OFERTABOLSASWSDL_QNAME);
    }

    public OfertaBolsasWSDL_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OFERTABOLSASWSDL_QNAME, features);
    }

    public OfertaBolsasWSDL_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OfertaBolsasWSDL_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OfertaBolsasWSDL
     */
    @WebEndpoint(name = "ofertaBolsasWSDLSOAP")
    public OfertaBolsasWSDL getOfertaBolsasWSDLSOAP() {
        return super.getPort(new QName("http://www.clarochile.cl/webservices/ofertaBolsasWSDL/", "ofertaBolsasWSDLSOAP"), OfertaBolsasWSDL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OfertaBolsasWSDL
     */
    @WebEndpoint(name = "ofertaBolsasWSDLSOAP")
    public OfertaBolsasWSDL getOfertaBolsasWSDLSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.clarochile.cl/webservices/ofertaBolsasWSDL/", "ofertaBolsasWSDLSOAP"), OfertaBolsasWSDL.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OFERTABOLSASWSDL_EXCEPTION!= null) {
            throw OFERTABOLSASWSDL_EXCEPTION;
        }
        return OFERTABOLSASWSDL_WSDL_LOCATION;
    }

}
